version: "3.9"
services:
  nginx:
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  bookmark:
    image: bookmarkorg/bookmark:latest
    container_name: bookmark-app
    restart: on-failure
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BOOKMARK_ARCHIVE_DELAY: ${BOOKMARK_ARCHIVE_DELAY}
      MIX_ENV: prod
    depends_on:
      - bookmark-db
      - archivebox
    ports:
      - '4000:4000'
    env_file:
      - base.env
    volumes:
      - ./priv/static/archive:/app/lib/bookmark-0.1.0/priv/static/archive

  bookmark-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookmark_dev
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  nostr-client:
    image: bookmarkorg/nostr-client:latest
    ports:
      - '5005:5005'

  archivebox:
    image: bookmarkorg/archivebox-server:latest
    ports:
      - '5001:5000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # TODO: Archivebox Server must take environment variables to enable these properties
    # environment:
    #     - PROPERTY=VALUE
    volumes:
      - ./priv/static/archive:/app/archivebox

volumes:
  db:
    driver: local