version: "3.9"
services:
  bookmark:
    image: bookmark:latest
    container_name: bookmark-app
    restart: on-failure
    command: sh -c "mix ecto.setup && mix phx.server"
    environment:
      MIX_ENV: prod
    depends_on:
      - bookmark-db
    ports:
      - '4000:4000'
    env_file:
      - base.env

  bookmark-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookmark_dev
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local