version: "3.9"
services:
  bookmark:
    image: ${DOCKER_REGISTRY}/bookmark:latest
    container_name: bookmark-app
    restart: on-failure
    environment:
      MIX_ENV: prod
    depends_on:
      - bookmark-db
      - archivebox
    ports:
      - '4000:4000'
    env_file:
      - base.env
    volumes:
      - ./priv/static/archive:/app/lib/bookmark-0.1.0/priv/static/archive

  bookmark-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookmark_dev
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  archivebox:
    image: ${DOCKER_REGISTRY}/archivebox-server:latest
    ports:
        - '5000:5000'
    # TODO: Archivebox Server must take environment variables to enable these properties
    # environment:
    #     - PROPERTY=VALUE
    volumes:
      - ./priv/static/archive:/app/archivebox

volumes:
  db:
    driver: local