version: "3.9"
services:
  bookmark-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookmark_dev
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  nostr-client:
    image: bookmarkorg/nostr-client:latest
    ports:
      - '5005:5005'

  archivebox:
    image: bookmarkorg/archivebox-server:latest
    ports:
        - '5001:5000'
    # TODO: Archivebox Server must take environment variables to enable these properties
    # environment:
    #     - PROPERTY=VALUE
    volumes:
      - ./priv/static/archive:/app/archivebox

volumes:
  db:
    driver: local